name: Create a versioned release

on:
  push:
    tags:
      - "v[0-9]+.*"

  workflow_dispatch: # trigger manually
    inputs:
      tag_version:
        description: "Release tag e.g. v1.0.1"
        required: true
        default: ""

jobs:
  fossa:
    uses: ./.github/workflows/fossa.yaml
    secrets: inherit

  create_docker_release:
    needs: fossa
    runs-on: [self-hosted, ubuntu-22-04, regular]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.12.0"

      - name: Create release tag
        id: determine-tag
        run: |
          if [ -n "${{ github.event.inputs.tag_version }}" ]; then
            TAG_VERSION="${{ github.event.inputs.tag_version }}"
            if [[ ! "$TAG_VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9]+)?$ ]]; then
              echo "Invalid tag format: $TAG_VERSION"
              exit 1
            fi
            echo "Creating new release tag: $TAG_VERSION"
            git tag -a "$TAG_VERSION" -m "Release $TAG_VERSION"
            git push origin "$TAG_VERSION"
            echo "has_tag=true" >> $GITHUB_OUTPUT
            echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
          else
            TAG_VERSION=${GITHUB_REF#refs/tags/}
            if [[ ! "$TAG_VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9]+)?$ ]]; then
              echo "Invalid tag format: $TAG_VERSION"
              exit 1
            fi
            echo "has_tag=true" >> $GITHUB_OUTPUT
            echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
          fi

      - name: Debug release tag
        if: ${{ steps.determine-tag.outputs.has_tag == 'true' }}
        run: |
          echo "Release tag created successfully: ${{ env.TAG_VERSION }}"

      - name: Build and push Docker Image
        if: ${{ steps.determine-tag.outputs.has_tag == 'true' }}
        id: build-and-push
        uses: ./.github/build-push-docker
        with:
          tag_version: ${{ env.TAG_VERSION }}
          github_token: ${{ github.token }}
